# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  branches:
    include:
      - main
      - feature-*

pool:
  vmImage: ubuntu-latest

steps:
- task: GoTool@0
  displayName: Setup Go version 1.18
  inputs:
    version: 1.18

- task: Go@0
  displayName: Go build
  inputs:
    command: 'build'
    arguments: '-v ./...'

- task: Go@0
  displayName: Go coverage test
  inputs:
    command: 'test'
    arguments: '-covermode=count ./...'

